#!/bin/bash

revert() {
  xset dpms 0 0 0
}

trap revert HUP INT TERM

xset dpms 3 3 3

if [[ $1 == '-n' ]]; then
  WP=$2
  revert
else
  WP=$1
fi

insidecolor=00000000
ringcolor=ffffffff
keyhlcolor=d23c3dff
bshlcolor=d23c3dff
separatorcolor=00000000
insidevercolor=00000000
insidewrongcolor=d23c3dff
ringvercolor=ffffffff
ringwrongcolor=ffffffff
verifcolor=ffffffff
timecolor=ffffffff
datecolor=ffffffff
loginbox=00000066
font="monospace"
font_time="monospace"
locktext=$(date +%A),\ $(date --iso-8601=date)

i3lock \
  -n -t -i "$WP" \
  -c "000000FF" \
  --refresh-rate=0.2 \
  --timepos='x-2410:h+150' \
  --datepos='x-2480:h+175' \
  --clock --date-align 1 --datestr "$locktext" \
  --insidecolor=$insidecolor --ringcolor=$ringcolor --line-uses-inside \
  --keyhlcolor=$keyhlcolor --bshlcolor=$bshlcolor --separatorcolor=$separatorcolor \
  --insidevercolor=$insidevercolor --insidewrongcolor=$insidewrongcolor \
  --ringvercolor=$ringvercolor --ringwrongcolor=$ringwrongcolor --indpos='x-2270:h+150' \
  --radius=20 --ring-width=4 --veriftext='' --wrongtext='' \
  --verifcolor="$verifcolor" --timecolor="$timecolor" --datecolor="$datecolor" \
  --time-font="$font_time" --date-font="$font" --layout-font="$font" --verif-font="$font" --wrong-font="$font" \
  --noinputtext='' --force-clock $lockargs

revert
